### PR TITLE
Updated compatibility for Gravity Forms > 1.9

### PR DESCRIPTION
**Pull request by eggolaz**
Gravity forms > 1.9 does not work with this plugin anymore - this small patch fixes the issue.

### CODE REVIEW

**Comment by tyxla** [comment]
Thanks for your contribution @eggolaz! Would you like to also update the unit tests, so they comply with this change?

**Comment by eggolaz** [comment]
Apologies @tyxla I will update to comply with the unit tests.

**Comment by tyxla** [comment]
Thanks for that @eggolaz! Feel free to /cc me when you feel this is ready.

**Comment by eggolaz** [comment]
Hi @tyxla have now updated to add the unit tests in.

**Comment by tyxla** [comment]
Hey @eggolaz! I appreciate your efforts, but tests are still failing here. Have you tested the solution? Do you need any help getting this to work properly?

**Comment by eggolaz** [comment]
Hi @tyxla do you know if the changes are ok?

**Comment by tyxla** [comment]
@eggolaz it appears they're not - tests should not be failing. It appears there is an unexpected array to string conversion. You can take a look here for more information about the failure (error varies depending on the PHP version): 

https://travis-ci.org/tyxla/Gravity-Forms-Multiple-Form-Instances/jobs/167038044
https://travis-ci.org/tyxla/Gravity-Forms-Multiple-Form-Instances/jobs/167038054

**Comment by eggolaz** [comment]
Hi @tyxla apologies about this, I have tested it functionally but not with unit tests. I'll have a look at this on the weekend if that's ok? If so, after I get it passing the unit tests I'll get back to you on here.

**Comment by tyxla** [comment]
Sounds great @eggolaz! I appreciate your diligence on this issue. Please let me know if I can assist with anything.

**Comment by tyxla** [comment]
Thank you @eggolaz for the contribution! Tests have been fixed in #22, so I'll close this one. 

This will be included in the next version. Again, thank you!

**Pull request closed without merging**
